
#ifndef	_SINMONSTER_HEADER_

#define _SINMONSTER_HEADER_



#define MONSTER_BAGON				1
#define MONSTER_SKELETON_WARRIOR	2
#define MONSTER_HEAD_CUTTER			3
#define MONSTER_ARMORED_BETTLE		4
#define MONSTER_SKELETON_RANGER		5
#define MONSTER_TITAN				6



#endif
