
#define filenameHack		"%s\\%d-%d.log"		
#define filenameDebugLogin		"%s\\%d-%d.log"
#define filenameCollectMoney	"%s\\%d-%d.txt"
#define filenameHackLogMoney	"%s\\(Gold)%d-%d.log"
#define filenameGetHighItem		"%s\\(Item)%d-%d.log"
#define filenameDeleteCharacter		"%s\\(Delete Character)%d-%d.log"
#define filenameDeleteCharactererror	"%s\\(Delete Character)%d-%d.log"
#define filenameBlackUser				"%s\\(Black User)%d-%d.log"
#define filenameMixItem		"%s\\(Mix)%d-%d.log"
#define filenameAgingItem		"%s\\(Aging)%d-%d.log"
#define filenameBlessCaslte		"%s\\(BlessCastle)%d-%d.log"


#define filenameSmeltingItem	"%s\\(Smelting) %d-%d.log"

#define filenameManufactureItem	"%s\\(Manufacture) %d-%d.log"

#define	filenameMixtureResetItem	"%s\\(믹스쳐리셋)%d월%d일.log"


#define MovieBloodyBattleLog	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s )"
#define filenameMovieBloodyBattleItem	"%s\\%d-%d.log"



#define msg1000		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Copied Item ( %d )\r\n"
#define msg1010		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Copied Item in Warehouse ( %d )\r\n"
#define msg1011		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Warehouse Gold ( %d )\r\n"
#define msg1100		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Crack/Hack Detected ( %s )\r\n"
#define msg1101		"%d:%d:%d - Name:( %s ) / IP ( %s ) Focus Changed ( %s )\r\n"
#define msg1102		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Checksum Error ( %d )\r\n"
#define msg1103		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Process Checksum Error ( %d )( %s )\r\n"
#define msg1110		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory Function Code Error ( %d )( %d )\r\n"
#define msg1120		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory Function Code Error2 ( %d )( %d )\r\n"
#define msg1130		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Function Checking Error ( %d )( %d )\r\n"
#define msg1132		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Function Checking Count Error ( %d )( %d )\r\n"

#define msg1150		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Gold Limit Exceeded, Potion Copy Attempt ( %d )( %d )\r\n"
#define msg1200		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Speed Hack ( %d )\r\n"
#define msg1250		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Time Error - Speed Hack ( %d )( %d )\r\n"
#define msg1400		"%d:%d:%d - Name:( %s ) / IP ( %s ) Time Mismatch ( %d )\r\n"
#define msg1500		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Attack Ratio Error ( %d )\r\n"
#define msg1510		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Potion Check Error ( %d )\r\n"
#define msg1530		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Potion Count Error ( %d )( %d )\r\n"

#define msg1600		"%d:%d:%d - Name:( %s ) / IP ( %s ) Character Info Save Error ( %d )\r\n"
#define msg1800		"%d:%d:%d - Name:( %s ) / IP ( %s ) XP Gain Error ( %d )\r\n"
#define msg1810		"%d:%d:%d - Name:( %s ) / IP ( %s ) XP Gain Character Error ( %d )\r\n"
#define msg1820		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Default Attack Rating Error ( %d )\r\n"
#define msg1821		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Default Attack Size Error ( %d )\r\n"
#define msg1823		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Continuous Attack Error ( %d )\r\n"
#define msg1830		"%d:%d:%d - Name:( %s ) / IP ( %s ) Skill Attack Rating Error ( %d )\r\n"
#define msg1833		"%d:%d:%d - Name:( %s ) / IP ( %s ) Skill Contunuous Attack Error ( %d )\r\n"
#define msg1840		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Restricted Area Trespassed ( %d )( %d )\r\n"
#define msg1900		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Weight Error ( %d )\r\n"

#define msg1950		"%d:%d:%d - Name:( %s ) / IP ( %s ) Item Error ( %d )\r\n"
#define msg1960		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Copied Item Recall ( %d ) ( %d )\r\n"
#define msg2000		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Forced Penalty Boot ( %d ) ( %d )\r\n"
#define msg2100		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Rapid Level Increase ( %d ) ( %d )\r\n"
#define msg2110		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Rapid XP Increase ( %d ) ( %d )\r\n"
#define msg2120		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Fast XP Increase / Lv( %d ) Xp( %d ) Mn( %d )\r\n"
#define msg2300		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Saved Level Error ( %d ) ( %d )\r\n"
#define msg2400		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Saved Item Error ( %d ) ( %d )\r\n"
#define msg2700		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Continuous Save Failed Error ( %d ) ( %d )\r\n"
#define msg2800		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Account Character Error ( %s ) ( %d ) ( %d )\r\n"
#define msg4000		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Trade Authorization Error ( %d ) ( %d )\r\n"
#define msg4100		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Money Transfer Error ( %d ) ( %d )\r\n"
#define msg5000		"%d:%d:%d - Multiple connections from same IP ( %d , %d )\r\n"
#define msg5100		"%d:%d:%d - Name:( %s %s ) / IP ( %s ) Too many packets ( %d )( %d )\r\n"
#define msg5200		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Game Server IP Error ( %d )( %s )\r\n"
#define msg6000		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Start Character Error  ( %d )( %d )\r\n"
#define msg6100		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Level Error ( %d )( %d )\r\n"
#define msg6200		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Level vs EXP Error ( %d )( %d )\r\n"
#define msg6500		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server and Client Exp Error ( %d )( %d ) - %d\r\n"
#define msg6510		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server and Client Moeny Error ( %d )( %d ) - %d\r\n"
#define msg6600		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server EXP Error ( %dk )( %dk )\r\n"
#define msg6610		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Money Error ( %d )( %d )\r\n"
#define msg6611		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Money Error2 ( %d )( %d )\r\n"
#define msg6612		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Money Error3 ( %d )( %d )\r\n"
#define msg6620		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) SubExp Over 50% Error ( %d )( %d )\r\n"
#define msg6630		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client EXP Error ( %d )/( %dk )( %dk )\r\n"
#define msg6800		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Item Code Error ( %d )-( %d )( %d )\r\n"
#define msg6810		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Item Temp Code Error ( %d )-( %d )( %d )\r\n"
#define msg6900		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Character State Error ( %d )( %d )\r\n"
#define msg6910		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Character SkillPoint Error ( %d )( %d )\r\n"
#define msg6920		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Character Weight Error ( %d )( %d )\r\n"
#define msg7000		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Process Time Out ( %d )( %d )\r\n"
#define msg7010		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Inventory Item Error ( %d )( %d )\r\n"
#define msg7020		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Charactor Model Error ( %d )( %s )( %s )\r\n"
#define msg7030		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Job Code Error ( %d )/( %d )( %d )\r\n"

#define msg7100		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Attack/Defence Error ( %d )( %d )( %d )\r\n"
#define msg7110		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Energy Bar Error ( %d )( %d )( %d )\r\n"
#define msg7120		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Recving Exp Error ( %d )( %d )( %d )\r\n"
#define msg7130		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Copied Item from floor ( %s )( %d )( %d )\r\n"
#define msg7140		"%d:%d:%d - ID:( %s ) / IP ( %s ) Tried to Connect Disable IP\r\n"
#define msg7150		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) [Item] Error from Inventory ( %d )( %d )( %d )\r\n"
#define msg7160		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) [Money] Error from Inventory ( %d )( %d )( %d )\r\n"

#define msg8000		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Inventory [Item] Error ( %d ) - ( %s )( %d )( %d / %d )\r\n"
#define msg8010		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Inventory [Money] Error ( %d ) - ( %d )( %d )\r\n"
#define msg8020		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server To Server Moving Item Error ( %d ) - ( %d )( %d )\r\n"
#define msg8030		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Wrong [Saving Charactor Name] ( %s )( %s )( %s )\r\n"
#define msg8040		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Item Position Error ( %d )( %d )( %d )\r\n"
#define msg8050		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Inventory Used Full ( %d )( %d )( %d )\r\n"
#define msg8060		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Used Item Code Warning ( %d )( %d )( %d )\r\n"
#define msg8070		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Inventory Loading Found [Copied Item] ( %d ) - ( %s )( %d )( %d / %d )\r\n"
#define msg8080		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory Buffer Saving Error ( %d )( %d )( %d )\r\n"
#define msg8100		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Warning AutoMouse ( %d )\r\n"
#define msg8102		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Warning MacroMouse ( %d )( %d )( %d )\r\n"
#define msg8110		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Warning Avg.Damage( Defence ) ( %d )( %d )/( %d )\r\n"
#define msg8120		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Warning Avg.Damage( Attack ) ( %d )( %d )/( %d )\r\n"
#define msg8140		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Time Out [nSPRITE] ( %d )( %d )\r\n"
#define msg8200		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Aging Failed [Copied Item - Sheltom] ( %d )( %d / %d )\r\n"
#define msg8210		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Aging Failed [Copied Item] ( %d )( %d / %d )( %d / %d )\r\n"
#define msg8300		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Reconnect Server ( %d )\r\n"
#define msg8400		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Checked Inventory Data [Disconnected]( %d )( %d )\r\n"
#define msg8500		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Damage Packet Error( %d )( %d )( %d )\r\n"
#define msg8510		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Limit Damage Over ( %d )( %d %d %d )( %d %d %d )\r\n"
#define msg8520		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Warning [Motion Speed] ( %d )\r\n"
#define msg8530		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Warning [Skill Attack] ( %d )\r\n"
#define msg8540		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Warning [Skill Forgery] ( %d )( %d )\r\n"
#define msg8550		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Warning [Skill Forgery - 2] ( %d )( %d )( %d )\r\n"
#define msg8560		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Initial Character Level [ 32Bit EXP Error ] ( %d )( %d )\r\n"
#define msg8570		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Too Many Updated [Character Infomation] ( %d %d )( %d )\r\n"
#define msg8580		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Client Damage Packet Error ( %d )( %d )\r\n"
#define msg8600		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Warning invincible Mode ( %d )( %d )\r\n"
#define msg8700		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Disconnected by [np GAMEGUARD] ( %d )( %d )\r\n"
#define msg8710		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Time Out [np GAMEGUARD] ( %d )( %d )\r\n"
#define msg8720		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Find Surprise Module ( %s )( %d )\r\n"
#define msg8730		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Character State Error ( %d )( %d )( %d )\r\n"
#define msg8800		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Potion Error ( %d )( %d )( %d )\r\n"
#define msg8810		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Server Potion Moving Error ( [%d]  %d )/( %d )\r\n"
#define msg8820		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) LevelQuest Code Warning ( %d )( %d )\r\n"
#define msg8830		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Shop Buy a forgery Item   (ItemCode: %d )(Price: %d )\r\n"
#define msg8840		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) *Server Money overflow( %d ) - ( %s ) (%d)(%d) = (%d)\r\n"
#define msg8850		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Skill Used Level Error  ( Lv:%d )( Code:%d )\r\n"
#define msg8860		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Check PlayField Warning : Area([%d] X=%d Y=%d Z=%d) SubHeight(%d)\r\n"
#define msg8870		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Compare ClanCode Error : ClanCode( %d <> %d ) ClanMaster(%d)\r\n"
#define msg8880		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Model File Error (%s)(%s)\r\n"
#define msg8890		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Warning Character Reloading (%s)(%s)(%d)\r\n"
#define msg8900		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Field NPC Warning ( Field: %d )( %d )\r\n"
#define msg8910		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Item Mesh Error ( %d )( %d )\r\n"
#define msg8920		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Illegally server connect\r\n"

#define msg8930		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) XignCode Report [Return : %s] [detail : %s]\r\n"

#define msg10000	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory SaveName Error 1 ( %s )( %s )\r\n"
#define msg10001	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory SaveName Error 2 ( %s )( %s )\r\n"
#define msg10002	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory SaveName Error 3 ( %s )( %s )\r\n"
#define msg10003	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory SaveName Error 4 ( %s )( %s )\r\n"
#define msg10005	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Memory Save Error 5 ( %s )( %s )\r\n"
#define msg10006	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Initial Save Memory Error ( %s )( %s )\r\n"
#define msg10007	"%d:%d:%d - SaveBuffer Point Error /IP ( %s ) / ( %d )( %d )\r\n"
#define msg10010	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Character Account Mismatch  ( %s )\r\n"
#define msg10020	"%d:%d:%d - ID:( %s ) / IP ( %s ) Authentication Error ( %s  %s )\r\n"
#define msg11000	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Shutdown Service\r\n"
#define msg21000	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Event High Score  ( %d )( %d )\r\n"

#define msgHack		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Hacking Alert ( %d )\r\n"
#define msgHack100	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Hacking Alert ( %d ) - Absorption( %d ) Attack Damage( %d ) Defence( %d )\r\n"
#define msgDebugloginID		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Debug Login ( %d )\r\n"
#define msgDebugloginIP		"%d:%d:%d - Name:( %s ) / IP ( %s ) Debug Login ( %d )\r\n"
#define msgKindPeople		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) Donations ( %d Gold ) Today's Total( %d Gold )\r\n"
#define msgHackMoney		"%d:%d:%d - Name:( %s ) Level( %d ) Money ( %d )\r\n"
#define	msgHighItem		"%d:%d:%d - Name:( %s ) Level( %d ) Item( %s ) Code( %d ) Unique Number( %d %d ) Spec Code( %d ) New( %d )\r\n"
#define msgCharDelete1		"%d:%d:%d - ID( %s ) Name( %s ) IP( %s ) Level( %d ) XP( %d ) Money ( %d )\r\n"
#define msgCharDelete2		"%d:%d:%d - ID( %s ) Name( %s ) Character Error\r\n"
#define msgMixItem			"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) - Item ( %s ) ( %d %d <%d> ) -> ( %d %d <%d> )\r\n"


#define msgSmeltingItem		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) - Item ( %s ) ( %d %d <%d> )\r\n"

#define msgManufactureItem	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) - Item ( %s ) ( %d %d <%d> )\r\n"

#define	msgMixtureResetItem		"%d시%d분%d초 - ID:( %s ) / Name:( %s ) / IP ( %s ) - 아이템( %s ) ( %d %d <%d> )\r\n"

#define msgAgingItem		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) - Aging Item    ( %s ) [%d] ( %d %d <%d> ) -> ( %d %d <%d> )\r\n"
#define msgAgingUpItem		"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) - Aging Up      ( %s ) [%d] ( %d %d <%d> ) -> ( %d %d <%d> )\r\n"
#define msgAgingFailItem	"%d:%d:%d - ID:( %s ) / Name:( %s ) / IP ( %s ) - Aging Failed  ( %s ) [%d] ( %d %d <%d> )\r\n"

#define msgBlackUser		"%d:%d:%d - ID( %s ) - ( %d )\r\n"

